Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: huggingface_hub in /home/ubuntu/.local/lib/python3.13/site-packages (0.35.3)
Requirement already satisfied: filelock in /home/ubuntu/.local/lib/python3.13/site-packages (from huggingface_hub) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in /home/ubuntu/.local/lib/python3.13/site-packages (from huggingface_hub) (2025.9.0)
Requirement already satisfied: packaging>=20.9 in /home/ubuntu/.local/lib/python3.13/site-packages (from huggingface_hub) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3/dist-packages (from huggingface_hub) (6.0.2)
Requirement already satisfied: requests in /home/ubuntu/.local/lib/python3.13/site-packages (from huggingface_hub) (2.32.5)
Requirement already satisfied: tqdm>=4.42.1 in /home/ubuntu/.local/lib/python3.13/site-packages (from huggingface_hub) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/ubuntu/.local/lib/python3.13/site-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /home/ubuntu/.local/lib/python3.13/site-packages (from huggingface_hub) (1.1.10)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/ubuntu/.local/lib/python3.13/site-packages (from requests->huggingface_hub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/ubuntu/.local/lib/python3.13/site-packages (from requests->huggingface_hub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/ubuntu/.local/lib/python3.13/site-packages (from requests->huggingface_hub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/ubuntu/.local/lib/python3.13/site-packages (from requests->huggingface_hub) (2025.10.5)
